# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170522_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='myapp.Student'),
        ),
    ]
