# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170523_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
