# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 11:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numpage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
